title: Sneha Katwal
email: skatwal222@gmail.com
description: >-
  Electronics, Communication, and Information Engineering student passionate about backend systems, computer vision, and tech inclusion.
baseurl: ""
url: "https://snehakatwal.com.np"
github_username: snehakatwal
linkedin_username: sneha-katwal

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
